version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rate
      POSTGRES_DB: rate
    ports:
      - "5431:5432"
    healthcheck:
      test: pg_isready -U postgres -d rate
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    container_name: rate_migrate
    depends_on:
      db:
        condition: service_healthy
    image: arigaio/atlas:latest
    volumes:
      - "./migrations:/tmp/migrations"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    command: >
      schema apply \
        --auto-approve \
        --url postgres://postgres:rate@10.5.0.10:5432/rate?sslmode=disable \
        --to "file://tmp/migrations/schema.hcl" \
        --dev-url postgres://postgres:rate@10.5.0.10:5432/rate?sslmode=disable

  bootstrap:
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    image: "gossip-price"
    environment:
      GP_BOOTSTRAP: "true"
      GP_CONNECTIONADDR: "/ip4/0.0.0.0/tcp/8000"
      GP_BOOTSTRAPADDR: ""
      GP_DATABASEURL: "postgres://postgres:rate@10.5.0.10:5432/rate?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  node1:
    image: "gossip-price"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    environment:
      GP_BOOTSTRAP: "false"
      GP_CONNECTIONADDR: "/ip4/0.0.0.0/tcp/8001"
      GP_BOOTSTRAPADDR: "/ip4/10.5.0.3/tcp/8000/p2p/12D3KooWNKned68ut2K6r6kniCzLqTdw4mi3rH69TWEEhzkTMnaH"
      GP_MINIMUMSIGNERCOUNT: "3"
      GP_DATABASEURL: "postgres://postgres:rate@10.5.0.10:5432/rate?sslmode=disable"
      GP_FETCHPRICEINTERVAL: "60"
    depends_on:
      db:
        condition: service_healthy
    links:
      - bootstrap

  node2:
    image: "gossip-price"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    environment:
      GP_BOOTSTRAP: "false"
      GP_CONNECTIONADDR: "/ip4/0.0.0.0/tcp/8002"
      GP_BOOTSTRAPADDR: "/ip4/10.5.0.3/tcp/8000/p2p/12D3KooWNKned68ut2K6r6kniCzLqTdw4mi3rH69TWEEhzkTMnaH"
      GP_MINIMUMSIGNERCOUNT: "3"
      GP_DATABASEURL: "postgres://postgres:rate@10.5.0.10:5432/rate?sslmode=disable"
      GP_FETCHPRICEINTERVAL: "60"
    depends_on:
      db:
        condition: service_healthy
    links:
      - bootstrap

  node3:
    image: "gossip-price"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    environment:
      GP_BOOTSTRAP: "false"
      GP_CONNECTIONADDR: "/ip4/0.0.0.0/tcp/8003"
      GP_BOOTSTRAPADDR: "/ip4/10.5.0.3/tcp/8000/p2p/12D3KooWNKned68ut2K6r6kniCzLqTdw4mi3rH69TWEEhzkTMnaH"
      GP_MINIMUMSIGNERCOUNT: "3"
      GP_DATABASEURL: "postgres://postgres:rate@10.5.0.10:5432/rate?sslmode=disable"
      GP_FETCHPRICEINTERVAL: "60"
    depends_on:
      db:
        condition: service_healthy
    links:
      - bootstrap

  node4:
    image: "gossip-price"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    environment:
      GP_BOOTSTRAP: "false"
      GP_CONNECTIONADDR: "/ip4/0.0.0.0/tcp/8004"
      GP_BOOTSTRAPADDR: "/ip4/10.5.0.3/tcp/8000/p2p/12D3KooWNKned68ut2K6r6kniCzLqTdw4mi3rH69TWEEhzkTMnaH"
      GP_MINIMUMSIGNERCOUNT: "3"
      GP_DATABASEURL: "postgres://postgres:rate@10.5.0.10:5432/rate?sslmode=disable"
      GP_FETCHPRICEINTERVAL: "60"
    depends_on:
      db:
        condition: service_healthy
    links:
      - bootstrap
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1